### PR TITLE
structure

### PR DESCRIPTION
**Pull request by Noreldin-S**
Added structure

### CODE REVIEW

**Comment by Noreldin-S** [comment]
added structure

**Comment by Noreldin-S** [comment]
built structure

**Review by clintrizzo — APPROVED** [review]

**Comment by clintrizzo** [comment]
the main pages are set up

**Review by clintrizzo — APPROVED** [review]

**Review by clintrizzo — COMMENTED** [review]
gffhfd

**Review by Noreldin-S — COMMENTED** [review]
sdv

**Review by Noreldin-S — COMMENTED** [review]
sturcutre added

**Pull request closed without merging**
